language: lisp
sudo: required

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

# either use a local install.sh script or install it via curl. Feel
# free to simplify this section in your own .travis.yml file.
install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi

script:
  - cl -l fiveam
       -e '(setf fiveam:*debug-on-error* t
                 fiveam:*debug-on-failure* t)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore h))
                   (trivial-backtrace:print-backtrace c :output *standard-output*)
                   (uiop:quit -1)))'
       -e '(ql:quickload :wt.html)'
       -e '(ql:quickload :wt.json)'
       -e '(ql:quickload :wt.http)'
       -e '(ql:quickload :wt.http/test)'
       -e '(nst:nst-cmd :run-package :http-test)'
       -e '(ql:quickload :wt.websocket)'

notifications:
  email:
    - xh@coobii.com
