language: lisp
sudo: required

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

python:
  - "2.7"

# Either use a local install.sh script or install it via curl. Feel
# free to simplify this section in your own .travis.yml file.
install:
  - sudo pip install autobahntestsuite
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi

script:
  - echo $(which wstest)
  - if [ "$LISP" = "sbcl" ]; then
      sbcl --non-interactive
           --eval '(setf *debugger-hook*
                     (lambda (c h)
                        (declare (ignore h))
                        (trivial-backtrace:print-backtrace c :output *standard-output*)
                        (uiop:quit -1)))'
           --eval '(asdf:test-system :wt)'
    elif [ "$LISP" = "ccl" ]; then
      ccl --eval '(setf *debugger-hook*
                    (lambda (c h)
                      (declare (ignore h))
                      (trivial-backtrace:print-backtrace c :output *standard-output*)
                      (uiop:quit -1)))'
          --eval '(asdf:test-system :wt)'
          --eval '(uiop:quit)'
    fi

notifications:
  email:
    - xh@coobii.com
